name: Create and Upload Release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Source Files
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -y xfonts-75dpi xfonts-base libjpeg-turbo8
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6.1-2.jammy_amd64.deb
      - name: Build project
        run: |
          npm ci
          npm run compile
          npm run release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: microluxe20-core
          path: release/*.zip
          retention-days: 30

  upload-release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: microluxe20-core
          path: release/
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release/*.zip
          draft: true
          prerelease: false